# Practica 1: Compuertas Cuanticas con Algebra Lineal
***
Rodriguez Nuñez Diego Eduardo

In [1]:
import numpy as np

In [2]:
#bases
ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])
ket00 = np.kron(ket0, ket0)  # |00⟩
ket01 = np.kron(ket0, ket1)  # |01⟩
ket10 = np.kron(ket1, ket0)  # |10⟩
ket11 = np.kron(ket1, ket1)  # |11⟩
ket000 = np.kron(ket0, np.kron(ket0, ket0))  # |000⟩
ket001 = np.kron(ket0, np.kron(ket0, ket1))  # |001⟩
ket010 = np.kron(ket0, np.kron(ket1, ket0))  # |010⟩
ket011 = np.kron(ket0, np.kron(ket1, ket1))  # |011⟩
ket110 = np.kron(ket1, np.kron(ket1, ket0))  # |110⟩

# Operadores 
X = np.array([[0, 1], [1, 0]])   
Y = np.array([[0, -1j], [1j, 0]])  
Z = np.array([[1, 0], [0, -1]])  

H = np.array([[1, 1], [1, -1]]) / np.sqrt(2) 

SWAP = np.array([[1, 0, 0, 0],
                 [0, 0, 1, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1]])  

CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])  

CZ = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, -1]]) 

CCNOT = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]]) 

CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]]) 

def R_psi(psi):
    return np.array([[np.cos(psi / 2), -np.sin(psi / 2)],
                     [np.sin(psi / 2), np.cos(psi / 2)]])

def aplicar_operador(nombre_op, operador, nombre_ket, ket):
    print(f"\nOperador {nombre_op} con estado {nombre_ket}")
    print("\nOperador:\n", operador)
    print("\nEstado inicial:\n", ket)
    result = np.dot(operador, ket)
    print("\nEstado final:\n", result)

# Diccionarios
operadores = {
    'X': X, 'Y': Y, 'Z': Z, 'H': H, 
    'SWAP': SWAP, 'CNOT': CNOT, 'CZ': CZ, 
    'CCNOT': CCNOT, 'CSWAP': CSWAP
}
kets = {
    '|0⟩': ket0, '|1⟩': ket1, '|00⟩': ket00, '|01⟩': ket01, 
    '|10⟩': ket10, '|11⟩': ket11, '|000⟩': ket000, '|001⟩': ket001, 
    '|010⟩': ket010, '|011⟩': ket011, '|110⟩': ket110
}

In [3]:
for nombre_op, op in operadores.items():
    for nombre_ket, ket in kets.items():
        try:
            aplicar_operador(nombre_op, op, nombre_ket, ket)
        except ValueError:
            continue


Operador X con estado |0⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[1]
 [0]]

Estado final:
 [[0]
 [1]]

Operador X con estado |1⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [1]]

Estado final:
 [[1]
 [0]]

Operador X con estado |00⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[1]
 [0]
 [0]
 [0]]

Operador X con estado |01⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [1]
 [0]
 [0]]

Operador X con estado |10⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [0]
 [1]
 [0]]

Operador X con estado |11⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [0]
 [0]
 [1]]

Operador X con estado |000⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

Operador X con estado |001⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

Operador X con estado |010⟩

Operador:
 [[0 1]
 [1 0]]

Estado inicial:
 [[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]

Operador X con estado |011⟩

Operador:
 [[0 1]
 [1 0]]

Es